services:
  postgres:
    container_name: postgres-sql-books
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-books
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-books
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

networks:
  spring-books:
    driver: bridge

volumes:
  postgres:
    driver: local